within IBPSA.Fluid.HeatPumps.Data.ScrollWaterToWater.Heating;
record SomeManufacturer_ABC060_70kW_4_0COP_R410A =
  IBPSA.Fluid.HeatPumps.Data.ScrollWaterToWater.Generic (
    volRat = 2.419187317237294,
    V_flow_nominal = 0.0029066588040134508,
    leaCoe = 0.003952462000342904,
    etaEle = 0.9125038193618816,
    PLos = 386.1906786026575,
    dTSup = 9.999999999999998,
    UACon = 26116.499272488043,
    UAEva = 56433.69799778423)

  annotation (
    defaultComponentPrefixes = "parameter",
    defaultComponentName="datHeaPum",
    preferredView="info",
  Documentation(info="<html>
<p>
Generated by Mr Modeler on 2026-07-13.
</p>
</html>"));