within IBPSA.Fluid.HeatPumps.Data.ScrollWaterToWater.Heating;
record SomeManufacturer_ABC060_70kW_4_0COP_R410A =
  IBPSA.Fluid.HeatPumps.Data.ScrollWaterToWater.Generic (
    volRat = 2.4027194561879153,
    V_flow_nominal = 0.002850143008484006,
    leaCoe = 0.0045118009062420136,
    etaEle = 0.8575208341877941,
    PLos = 386.74819597960413,
    dTSup = 0.01,
    UACon = 37598.90991968645,
    UAEva = 68390.46762112086)

  annotation (
    defaultComponentPrefixes = "parameter",
    defaultComponentName="datHeaPum",
    preferredView="info",
  Documentation(info="<html>
<p>
Generated by Mr Modeler on 2026-05-31.
</p>
</html>"));