within IBPSA.Fluid.HeatPumps.Data.ScrollWaterToWater.Heating;
record SomeManufacturer_ABC060_70kW_4_0COP_R410A =
  IBPSA.Fluid.HeatPumps.Data.ScrollWaterToWater.Generic (
    volRat = 2.4027194563571803,
    V_flow_nominal = 0.0028501430079744925,
    leaCoe = 0.004511800899262784,
    etaEle = 0.8575208340495368,
    PLos = 386.74819586370927,
    dTSup = 0.010000000000000082,
    UACon = 37598.909817595144,
    UAEva = 68390.46719060146)

  annotation (
    defaultComponentPrefixes = "parameter",
    defaultComponentName="datHeaPum",
    preferredView="info",
  Documentation(info="<html>
<p>
Generated by Mr Modeler on 2025-06-24.
</p>
</html>"));