within IBPSA.Fluid.HeatPumps.Data.ScrollWaterToWater.Heating;
record SomeManufacturer_ABC060_70kW_4_0COP_R410A =
  IBPSA.Fluid.HeatPumps.Data.ScrollWaterToWater.Generic (
    volRat = 2.421006715597859,
    V_flow_nominal = 0.002903220474646598,
    leaCoe = 0.004035038410701231,
    etaEle = 0.9055563453166017,
    PLos = 368.5617295092451,
    dTSup = 10.0,
    UACon = 27712.10830796358,
    UAEva = 57595.40364285681)

  annotation (
    defaultComponentPrefixes = "parameter",
    defaultComponentName="datHeaPum",
    preferredView="info",
  Documentation(info="<html>
<p>
Generated by Mr Modeler on 2026-07-13.
</p>
</html>"));